MENU_DISPONIVEL = [
    {"id": 1, "nome": "ADICIONAL FRANGO 50G", "preco": 4.0},
    {"id": 2, "nome": "SALADA", "preco": 18.0},
    {"id": 3, "nome": "ADICIONAL DE LEITE", "preco": 1.0},
    {"id": 4, "nome": "AMERICANO", "preco": 5.0},
    {"id": 5, "nome": "CAPUCCINO", "preco": 7.0},
    {"id": 6, "nome": "CARIOCA", "preco": 5.0},
    {"id": 7, "nome": "COADO", "preco": 6.0},
    {"id": 8, "nome": "COADO PEQUENO", "preco": 3.0},
    {"id": 9, "nome": "DUPLO MACCHIATO", "preco": 9.0},
    {"id": 10, "nome": "ESPRESSO", "preco": 5.0},
    {"id": 11, "nome": "ESPRESSO DUPLO", "preco": 8.0},
    {"id": 12, "nome": "FRENCH PRESS 300ML", "preco": 8.0},
    {"id": 13, "nome": "FRENCH PRESS 600ML", "preco": 14.0},
    {"id": 14, "nome": "LATTE", "preco": 7.0},
    {"id": 15, "nome": "MACCHIATO", "preco": 6.0},
    {"id": 16, "nome": "MOCCHA", "preco": 9.0},
    {"id": 17, "nome": "AFFOGATO", "preco": 8.0},
    {"id": 18, "nome": "COLD BREW", "preco": 8.0},
    {"id": 19, "nome": "LATTE GELADO", "preco": 7.0},
    {"id": 20, "nome": "MOCCHA GELADO", "preco": 10.0},
    {"id": 21, "nome": "STELLA ARTOIS 310ML", "preco": 6.0},
    {"id": 22, "nome": "CHÁ GELADO", "preco": 7.0},
    {"id": 23, "nome": "CHÁ QUENTE", "preco": 5.0},
    {"id": 24, "nome": "MATE BATIDO", "preco": 7.0},
    {"id": 25, "nome": "CHOCOLATE QUENTE", "preco": 8.0},
    {"id": 26, "nome": "DESAYUNO", "preco": 18.0},
    {"id": 27, "nome": "ADICIONAL GRANOLA", "preco": 1.0},
    {"id": 28, "nome": "BOLO FATIA", "preco": 5.0},
    {"id": 29, "nome": "BOLO NO POTE", "preco": 8.0},
    {"id": 30, "nome": "BRIGADEIRO", "preco": 2.0},
    {"id": 31, "nome": "BROWNIE CHOCOLATE", "preco": 5.0},
    {"id": 32, "nome": "COOKIE", "preco": 5.0},
    {"id": 33, "nome": "FOLHADO DOCE", "preco": 5.0},
    {"id": 34, "nome": "FRENCH TOAST", "preco": 5.0},
    {"id": 35, "nome": "QUICHE", "preco": 10.0},
    {"id": 36, "nome": "PÃO DE QUEIJO", "preco": 3.0},
    {"id": 37, "nome": "TORTA SALGADA", "preco": 8.0},
    {"id": 38, "nome": "PÃO INTEGRAL", "preco": 4.0},
    {"id": 39, "nome": "SUCO DE LARANJA", "preco": 6.0},
    {"id": 40, "nome": "SMOOTHIE DE FRUTAS", "preco": 10.0},
    {"id": 41, "nome": "CAFÉ GELADO", "preco": 7.0},
    {"id": 42, "nome": "MILKSHAKE", "preco": 12.0},
    {"id": 43, "nome": "SORVETE", "preco": 8.0},
    {"id": 44, "nome": "SANDUÍCHE NATURAL", "preco": 12.0},
    {"id": 45, "nome": "PIZZA BROTINHO", "preco": 15.0},
    {"id": 46, "nome": "TORRADA", "preco": 6.0},
    {"id": 47, "nome": "CROISSANT", "preco": 4.0},
    {"id": 48, "nome": "EMPADA", "preco": 5.0},
    {"id": 49, "nome": "MOUSSE DE CHOCOLATE", "preco": 6.0},
    {"id": 50, "nome": "PANQUECA", "preco": 7.0},
]
